version: "3.8"
services:
  # app:
  #   image: todo-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3000
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
